version = 0.1

[default.global.parameters]
stack_name = "sam-app-javascript-debugging"
region = "us-east-1"

[default.deploy.parameters]
capabilities = [ "CAPABILITY_IAM", "CAPABILITY_NAMED_IAM" ]
confirm_changeset = false
resolve_s3 = true
stack_name = "sam-app-javascript-debugging"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
