version = 0.1

[default.global.parameters]
stack_name = "sam-app-java-debugging"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = [ "CAPABILITY_IAM", "CAPABILITY_NAMED_IAM" ]
confirm_changeset = false
resolve_s3 = true
stack_name = "sam-app-java-debugging"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
